server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  这里有个坑 ，， mapper\*Mapper.xml  中的 \ / 在本机都可以访问，但是 \ 在导成jar包则不能访问，只能用 /
#  configuration:
#    interceptors: com.game.game.config.PageInterceptor
spring:
  datasource:
    url: jdbc:mysql://47.95.237.152:3306/playname?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hadoop@123


#logging:
#  level:
#    root: info
#  file:
#    name: E:/A/springSource/Log/test.log
    #    %d表示日期时间，
    #	%thread表示线程名，
    #	%-5level：级别从左显示5个字符宽度
    #	%logger{50} 表示logger名字最长50个字符，否则按照句点分割。
    #	%msg：日志消息，
    #	%n是换行符
#    max-size: 5MB
#    max-history: 30
#
#  pattern:
#    file: '%date{HH:mm:ss.SSS} == [%thread] ==  %-5level == %logger{36} - %msg%n'
##    console: '%d{yyyy-MM-dd-HH-mm} ==== [%t]  [%c] [%p] - %m%n'
#logging:
#  config: classpath:log\*
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: false
